### ISSUE TITLE
[Bug] Boot Service configuration parameter bootService.baseDir is ignored

### ISSUE THREAD

**Issue by ahm50menzies** [devhawala/dodo#22]
Hello,

Attempting to use a custom Boot Service directory is ignored by Dodo Clearinghouse startup and causes an exception stating Invalid base directory name.

Boot Service definition is:

```
#Boot service
startBootService = true
bootService.baseDir = /mnt/XNS/bootsvcfiles
bootService.verbose = true

```
When starting the Dodo Clearinghouse Service this exception is raised:
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid base directory name: bootsvc
	at dev.hawala.xns.level4.boot.BootResponder.<init>(BootResponder.java:90)
	at dev.hawala.xns.DodoServer.main(DodoServer.java:330)

```
The Boot Service (and thus the Clearinghouse Service) will **only** start if the boot service files are in a directory named **bootsvc** in the specific directory where the `run-dodoserver.sh` is launched from.

Kind regards,

Adrian

**Comment by devhawala** [comment]
Hello Adrian,

well, you seem to be the first person using this config parameter, so you had a fair chance to find the bug due to a typo in the Java code... (i use the defaults here myself)

The new version just uploaded should now match the documentation and find the specified location for the boot service files, but i did not test it (not much time left currently).

Greetings, Hans

**Comment by ahm50menzies** [comment]
Hi Hans,

Thanks so much for taking the time to sort this - it now works perfectly.

Regards,

Adrian
